CREATE TABLE NGANH (
    MaNganh CHAR(4) PRIMARY KEY NOT NULL,
    TenNganh VARCHAR(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE PHONG_XUONG (
    MaPhongXuong CHAR(10) PRIMARY KEY NOT NULL,
    TenPhongXuong VARCHAR(150) NOT NULL,
    ViTri VARCHAR(20),
    MaNganh CHAR(4) NOT NULL,
    FOREIGN KEY (MaNganh) REFERENCES NGANH(MaNganh)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE CANBO (
    MaCanBo VARCHAR(16) PRIMARY KEY NOT NULL,
    TenCanBo VARCHAR(100) NOT NULL,
    SoDienThoai VARCHAR(20),
    MaPhongXuong CHAR(10) NOT NULL,
    VaiTroQL VARCHAR(100),
    FOREIGN KEY (MaPhongXuong) REFERENCES PHONG_XUONG(MaPhongXuong)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE THIETBI (
    MaThietBi INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    TenThietBi VARCHAR(150) NOT NULL,
    ThongSoKyThuat VARCHAR(1000),
    NamSanXuat YEAR,
    NgayNhap DATETIME NOT NULL,
    SoLuong INT NOT NULL,
    DonViTinh VARCHAR(20),
    NuocSanXuat VARCHAR(20),
    HienTrang VARCHAR(20),
    GhiChu VARCHAR(200),
    MaPhongXuong CHAR(10),
    FOREIGN KEY (MaPhongXuong) REFERENCES PHONG_XUONG(MaPhongXuong)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE CHUYENTHIETBI (
    MaChuyen INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    MaThietBi INT NOT NULL,
    NgayChuyen DATETIME NOT NULL,
    MaPhongChuyen CHAR(10) NOT NULL,
    MaPhongNhan CHAR(10) NOT NULL,
    SoLuongChuyen INT NOT NULL,
    FOREIGN KEY (MaThietBi) REFERENCES THIETBI(MaThietBi),
    FOREIGN KEY (MaPhongChuyen) REFERENCES PHONG_XUONG(MaPhongXuong),
    FOREIGN KEY (MaPhongNhan) REFERENCES PHONG_XUONG(MaPhongXuong),
    CHECK (MaPhongNhan <> MaPhongChuyen)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE THANHLYTAISAN (
    MaThanhLy INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    MaThietBi INT NOT NULL,
    NgayThanhLy DATETIME NOT NULL,
    SoLuong INT NOT NULL,
    ThanhTien DECIMAL(19, 4) NOT NULL,
    FOREIGN KEY (MaThietBi) REFERENCES THIETBI(MaThietBi)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE MUATHIETBI (
    MaMua INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    MaThietBi INT NOT NULL,
    NgayMua DATETIME NOT NULL,
    SoLuongMua INT NOT NULL,
    GiaMua DECIMAL(19,4) NOT NULL,
    TongTien DECIMAL(19,4),
    NhaCungCap VARCHAR(200),
    FOREIGN KEY (MaThietBi) REFERENCES THIETBI(MaThietBi)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

DELIMITER //

CREATE TRIGGER trg_muathietbi_before_insert
BEFORE INSERT ON MUATHIETBI
FOR EACH ROW
BEGIN
    SET NEW.TongTien = NEW.SoLuongMua * NEW.GiaMua;
END;
//

CREATE TRIGGER trg_muathietbi_before_update
BEFORE UPDATE ON MUATHIETBI
FOR EACH ROW
BEGIN
    SET NEW.TongTien = NEW.SoLuongMua * NEW.GiaMua;
END;
//

DELIMITER ;

INSERT INTO NGANH VALUES
('CNTT', 'Công Nghệ Thông Tin'),
('KTCK', 'Kỹ Thuật Cơ Khí'),
('DDTU', 'Điện - Điện Tử');